"""add_source_id_to_infractions

Revision ID: caab0ebaa111
Revises: 53e3906540b5
Create Date: 2025-10-04 12:51:37.379101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caab0ebaa111'
down_revision: Union[str, Sequence[str], None] = '53e3906540b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infractions', sa.Column('source_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_infractions_source_id'), 'infractions', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_infractions_source_id'), table_name='infractions')
    op.drop_column('infractions', 'source_id')
    # ### end Alembic commands ###
