"""Criação inicial das tabelas de usuários e infrações

Revision ID: cfe2eca25961
Revises:
Create Date: 2025-09-27 15:02:24.300509

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cfe2eca25961"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "infractions",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("infraction_number", sa.String(length=255), nullable=False),
        sa.Column("process_number", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("sanction_type", sa.String(length=100), nullable=True),
        sa.Column("gravity", sa.String(length=50), nullable=True),
        sa.Column("fine_value", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("infraction_datetime", sa.DateTime(), nullable=False),
        sa.Column("fact_date", sa.Date(), nullable=True),
        sa.Column("system_launch_date", sa.Date(), nullable=True),
        sa.Column("last_updated_date", sa.DateTime(), nullable=True),
        sa.Column("offender_name", sa.TEXT(), nullable=False),
        sa.Column("offender_document", sa.String(length=255), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("infraction_type_description", sa.TEXT(), nullable=True),
        sa.Column("municipality", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("location_description", sa.TEXT(), nullable=True),
        sa.Column("longitude", sa.DECIMAL(precision=11, scale=8), nullable=True),
        sa.Column("latitude", sa.DECIMAL(precision=10, scale=8), nullable=True),
        sa.Column("affected_biomes", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("infraction_number"),
    )
    op.create_index(
        op.f("ix_infractions_infraction_datetime"),
        "infractions",
        ["infraction_datetime"],
        unique=False,
    )
    op.create_index(
        "ix_infractions_latitude_longitude",
        "infractions",
        ["latitude", "longitude"],
        unique=False,
    )
    op.create_index(
        op.f("ix_infractions_offender_document"),
        "infractions",
        ["offender_document"],
        unique=False,
    )
    op.create_index(
        op.f("ix_infractions_process_number"),
        "infractions",
        ["process_number"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_infractions_process_number"), table_name="infractions")
    op.drop_index(op.f("ix_infractions_offender_document"), table_name="infractions")
    op.drop_index("ix_infractions_latitude_longitude", table_name="infractions")
    op.drop_index(op.f("ix_infractions_infraction_datetime"), table_name="infractions")
    op.drop_table("infractions")
    # ### end Alembic commands ###
